# Usa una imagen base de JDK 17
FROM openjdk:17-jdk-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /springboot-project

# Copia el archivo JAR de la aplicación en el contenedor
COPY target/demo-3-0.0.1-SNAPSHOT.jar app.jar

# Expone el puerto en el que la aplicación se ejecuta
EXPOSE 8080

# Define el comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
